### ISSUE TITLE
Add a license to the repository

### ISSUE THREAD

**Issue by cbjuan** [FarzanaR11/Assignment-on-Qiskit-CSE-499B.6-#1]
I recently came across your project Assignment-on-Qiskit-CSE-499B.6- and I noticed that the repository github.com/FarzanaR11/Assignment-on-Qiskit-CSE-499B.6- currently does not have a license specified.

Why Adding a License is Important?

As [GitHub documents](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)
>Public repositories on GitHub are often used to share open source software. For your repository to truly be open source, you'll need to license it so that others are free to use, change, and distribute the software.

Would be possible to add a valid license to this repository? Probably something really OpenSource such as the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0) would fit really well.

Thanks!

**Comment by FarzanaR11** [comment]
Dear Dr. Juan Cruz-Benito,

Thank you for your suggestion regarding the addition of a license to my repository. I have now added the Apache 2.0 license to the repository, as it aligns well with my goals of contributing to the open-source community while protecting my intellectual property.

Your feedback was invaluable, and I appreciate your time in guiding me through this process.

Additionally, I have been following your work at IBM Quantum with great interest. Your contributions to quantum computing and open-source projects resonate with my own research interests. I have been developing quantum algorithms for error correction, quantum NLP with my native language Bengali NLP and drug discovery in machine learning and am keen to explore further advancements in this field.

Given our shared interests, I would be very interested in discussing potential collaboration opportunities or receiving any insights you might have regarding advancements in quantum computing.

Thank you once again for your support and guidance. I look forward to the possibility of connecting with you.

Best regards,
Farzana Rahman

LinkedIn Profile: https://www.linkedin.com/in/farzanarahman11/
GitHub Profile: https://github.com/FarzanaR11
Medium: https://medium.com/@farzanarahman3301
Gmail: farzanarahman3301@gmail.com
WhatsApp: https://wa.me/+8801744213969

**Comment by cbjuan** [comment]
Thanks!
